package com.aexp.gcs.pod.tools.templatemigration

import org.springframework.beans.factory.annotation.Value
import org.springframework.stereotype.Component

/**
 * This class is used as a holder of the Application configuration properties 
 * provided in the config/application.yml file or through the command line using
 * the --spring.config.location option
 *  
 * @author Victor Navarro
 */

@Component
class AppSettings
{
	/**
	 * Full path to the location of the files generated by Template Translation Tool
	 */
	@Value('${spring.application.sourceFolder}')
	String sourceFolder
	
	/**
	 * Where Migration Tool will be generating modules and copying files
	 */
	@Value('${spring.application.baseOutputFolder}')
	String outputFolder

	/**
	 * Location of the template-transaction-info module
	 */
	@Value('${spring.application.templateTransactionInfo}')
	String templateTransactionInfo
	
	/**
	 * Location of the object-model module
	 */
	@Value('${spring.application.objectModelLocation}')
	String objectModelLocation
	
	/**
	 * Location of the ValidationMessages.properties
	 */
	@Value('${spring.application.validationMessagesFile}')
	String validationMessagesFile
	
	/**
	 * Location of the validation XML files
	 */
	@Value('${spring.application.beanConstraintsFolder}')
	String beanConstraintsFolder
}
