List tables = ['TGPOA01.INT_ADVICERETRY_CHANNEL_MESSAGE', 'TGPOA01.INT_ADVICERETRY_GROUP_TO_MESSAGE', 'TGPOA01.INT_ADVICERETRY_MESSAGE', 'TGPOA01.INT_ADVICERETRY_MESSAGE_GROUP', 
                    'TGPOA01.INT_CLAIMCHECK_CHANNEL_MESSAGE', 'TGPOA01.INT_CLAIMCHECK_GROUP_TO_MESSAGE', 'TGPOA01.INT_CLAIMCHECK_MESSAGE', 'TGPOA01.INT_CLAIMCHECK_MESSAGE_GROUP', 
                    'TGPOA01.INT_CLEANUP_CHANNEL_MESSAGE', 'TGPOA01.INT_CLEANUP_GROUP_TO_MESSAGE', 'TGPOA01.INT_CLEANUP_MESSAGE', 'TGPOA01.INT_CLEANUP_MESSAGE_GROUP', 
                    'TGPOA01.INT_DISPATCH_CHANNEL_MESSAGE', 'TGPOA01.INT_DISPATCH_GROUP_TO_MESSAGE', 'TGPOA01.INT_DISPATCH_MESSAGE', 'TGPOA01.INT_DISPATCH_MESSAGE_GROUP',
                    'TGPOA01.INT_FAX_CHANNEL_MESSAGE', 'TGPOA01.INT_FAX_GROUP_TO_MESSAGE', 'TGPOA01.INT_FAX_MESSAGE', 'TGPOA01.INT_FAX_MESSAGE_GROUP', 
                    'TGPOA01.INT_CHANNEL_MESSAGE', 'TGPOA01.INT_GROUP_TO_MESSAGE', 'TGPOA01.INT_MESSAGE', 'TGPOA01.INT_MESSAGE_GROUP', 
                    'TGPOA01.INT_MFDISPATCH_CHANNEL_MESSAGE', 'TGPOA01.INT_MFDISPATCH_GROUP_TO_MESSAGE', 'TGPOA01.INT_MFDISPATCH_MESSAGE', 'TGPOA01.INT_MFDISPATCH_MESSAGE_GROUP',
                    'TGPOA01.INT_MFTIMEOUT_CHANNEL_MESSAGE', 'TGPOA01.INT_MFTIMEOUT_GROUP_TO_MESSAGE', 'TGPOA01.INT_MFTIMEOUT_MESSAGE', 'TGPOA01.INT_MFTIMEOUT_MESSAGE_GROUP', 
                    'TGPOA01.INT_RETRY_CHANNEL_MESSAGE', 'TGPOA01.INT_RETRY_GROUP_TO_MESSAGE', 'TGPOA01.INT_RETRY_MESSAGE', 'TGPOA01.INT_RETRY_MESSAGE_GROUP', 
                    'TGPOA01.INT_SMC_CHANNEL_MESSAGE', 'TGPOA01.INT_SMC_GROUP_TO_MESSAGE', 'TGPOA01.INT_SMC_MESSAGE', 'TGPOA01.INT_SMC_MESSAGE_GROUP', 
                    'TGPOA01.INT_SORRETRY_CHANNEL_MESSAGE', 'TGPOA01.INT_SORRETRY_GROUP_TO_MESSAGE', 'TGPOA01.INT_SORRETRY_MESSAGE', 'TGPOA01.INT_SORRETRY_MESSAGE_GROUP', 
                    'TGPOA01.INT_SORTIMEOUT_CHANNEL_MESSAGE', 'TGPOA01.INT_SORTIMEOUT_GROUP_TO_MESSAGE', 'TGPOA01.INT_SORTIMEOUT_MESSAGE', 'TGPOA01.INT_SORTIMEOUT_MESSAGE_GROUP', 
                    'TGPOA01.INT_SOR_CHANNEL_MESSAGE', 'TGPOA01.INT_SOR_GROUP_TO_MESSAGE', 'TGPOA01.INT_SOR_MESSAGE', 'TGPOA01.INT_SOR_MESSAGE_GROUP', 
                    'TGPOA01.INT_THGROUP_CHANNEL_MESSAGE', 'TGPOA01.INT_THGROUP_GROUP_TO_MESSAGE', 'TGPOA01.INT_THGROUP_MESSAGE', 'TGPOA01.INT_THGROUP_MESSAGE_GROUP', 
                    'TGPOA01.INT_THTIMEOUT_CHANNEL_MESSAGE', 'TGPOA01.INT_THTIMEOUT_GROUP_TO_MESSAGE', 'TGPOA01.INT_THTIMEOUT_MESSAGE', 'TGPOA01.INT_THTIMEOUT_MESSAGE_GROUP']
List oldNames = ['ADVICERETRY',  'CLAIMCHECK', 'CLEANUP', 'FAX', 'MFDISPATCH', 'MFTIMEOUT', 'RETRY', 'SMC', 'SORRETRY', 'SORTIMEOUT', 'SOR', 'THGROUP', 'THTIMEOUT']
List newNames = ['ADVRET',       'CLMCHK',     'CLNUP',   'FAX', 'MFDSPTCH',   'MFTOUT',    'RETRY', 'SMC', 'SORRET',   'SORTOUT',    'SOR', 'THGROUP', 'THTOUT']

oldNames.eachWithIndex{ oldPfx, oldPrxIdx ->
    tables.each{ String aTableName ->
        if (aTableName.indexOf("_${oldPfx}_") > 0) {
            String newTableName = aTableName.replace("INT_${oldPfx}", "${newNames[oldPrxIdx]}")
            println "RENAME TABLE ${aTableName} TO ${newTableName.substring(newTableName.indexOf('.') + 1)};"
            //println "${newTableName.substring(newTableName.indexOf('.') + 1)};"
        }
    }
}